# Generated by Django 5.0.4 on 2024-04-19 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unit_size',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Größe jeder Einheit des Materials, z.B. Länge, Breite, Gewicht, etc.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
    ]
