# Generated by Django 5.0.4 on 2024-04-19 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0002_material_unit_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='breite',
            field=models.DecimalField(decimal_places=2, default=60, help_text='Breite jeder Einheit des Materials in Metern', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='laenge',
            field=models.DecimalField(decimal_places=2, default=2900, help_text='Länge jeder Einheit des Materials in Metern', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
    ]
