# Generated by Django 5.0.4 on 2024-04-21 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0004_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='artikelnummer',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='material',
            name='gewicht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='material',
            name='lagerbestand',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
