# Generated by Django 5.0.4 on 2024-04-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0005_material_artikelnummer_material_gewicht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='rohstoff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
