# Generated by Django 5.0.4 on 2024-04-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0007_material_material_hoehe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='verpackungseinheit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
