# Generated by Django 5.0.4 on 2024-04-22 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0009_alter_material_lagerbestand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_hoehe',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
