# Generated by Django 5.0.4 on 2024-04-22 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0010_alter_material_material_hoehe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materialimp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nr', models.CharField(max_length=200, null=True)),
                ('Beschreibung', models.CharField(max_length=225)),
                ('Beschreibung_2', models.CharField(max_length=225)),
                ('Einkaufscode', models.CharField(max_length=50)),
                ('Länge_Basis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('Breite_Basis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('Stärke_Basis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('Menge_pro_Paket', models.DecimalField(blank=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('Basiseinheit', models.CharField(max_length=50)),
            ],
        ),
    ]
