# Generated by Django 5.0.4 on 2024-04-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0012_alter_materialimp_breite_basis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialimp',
            name='Breite_Basis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialimp',
            name='Länge_Basis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialimp',
            name='Menge_pro_Paket',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialimp',
            name='Stärke_Basis',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
