# Generated by Django 5.0.4 on 2024-04-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0013_alter_materialimp_breite_basis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materialimp',
        ),
    ]
