# Generated by Django 5.0.4 on 2024-04-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0014_delete_materialimp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='gewicht',
        ),
        migrations.RemoveField(
            model_name='material',
            name='lagerbestand',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_price_per_unit',
        ),
        migrations.RemoveField(
            model_name='material',
            name='rohstoff',
        ),
    ]
