# Generated by Django 5.0.4 on 2024-04-28 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0015_remove_material_gewicht_remove_material_lagerbestand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schraube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
        ),
    ]
