# Generated by Django 5.0.4 on 2024-04-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0016_schraube'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schraube',
        ),
    ]
