# Generated by Django 5.0.4 on 2024-05-09 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0017_delete_schraube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('hex_code', models.CharField(db_index=True, max_length=7, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='kategorie',
            name='farbe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Terrassenplaner.farbe'),
        ),
    ]
