# Generated by Django 5.0.4 on 2024-05-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Terrassenplaner', '0019_material_farbe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorie',
            name='farbe',
        ),
        migrations.RemoveField(
            model_name='material',
            name='farbe',
        ),
        migrations.DeleteModel(
            name='Farbe',
        ),
    ]
